version: 2.1

jobs:
  build:
    docker:
        - image: codenoodle/purescript
    steps:
    - checkout
    - restore_cache:
        name: Restore Cached Artifacts
        key: purescript-wordoku-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
    - run:
        name: Install Dev Dependencies
        command: npm install --unsafe-perm=true --allow-root
    - run:
        name: Update App Dependencies
        command: npm run-script install
    - run:
        name: Compile
        command: pulp build
    - run:
        name: Compile and Run Tests
        command: pulp test
    - save_cache:
        name: Cache Dependencies
        key: purescript-wordoku-dependencies-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
        paths:
            - "/root/output"
            - "/root/bower_components" 
                         
